version: "3.7"
services:
  ocrclient:
    container_name: "ocrclient"
    build: .
    environment:
      IMAGE_PATH: "/app/resource/Screenshot.png"
    volumes:
      - /Users/rbozhko/Desktop/:/app/resource

  ocrserver:
    container_name: "ocrserver"
    image: otiai10/ocrserver
    ports:
      - "8080:8080"
    environment:
      PORT: 8080